### DISCUSSION TITLE
wallos webhooks and home assistant

### DISCUSSION THREAD

**Discussion by lennon101** [ellite/Wallos#383] [Q&A] [answered]
This question might be better suited in the HA community, but I'm also hoping to get some advice here. Before I get started, is there any where that I can find documentation on the Wallos webhook? i.e what shape the data comes in etc? I'm trying to do some testing with the wallos webhook and using it to trigger a home assistant notification. HA has a webhook trigger but I'm struggling to understand how to extract the `multidict` that Wallos is sending. 

When Wallos sends a webhook, I get this in the HA automation traces (changed variables tab)

![image](https://github.com/ellite/Wallos/assets/1709944/da540faf-8d2f-43e6-9d09-73fb6dc8980e)

--- 
## triggering it manually: 

the config is currently set to the default and when I hit the test button, the HA automation actually fails to trigger at all. It only triggers when there is a real event. 

![image](https://github.com/ellite/Wallos/assets/1709944/e143700c-4b1a-406f-98ef-ac5bd0d4f17e)

**Comment by ellite** [comment]
Hi.  Sorry for the delay.
I never tried it with home assistant.

In theory it would be something like this:

let's assume you have notification for 1 day before, you are using the default payload and you didn't change de default {{subscriptions}} iterator. Netflix and Spotify are up for payment tomorrow..

```
{
    "days_until": "1",  // Default number of days before payment date that is set in the settings page
    "subscriptions": [
        {
            "name": "Netflix",
            "price": "15",
            "currency": "Euro",
            "category": "Entertainment",
            "date": "2024-06-21",
            "payer": "Your name" // As set in the household table
            "days": "1" // Actual number of days before payment date that will trigger the notification if is set on the subscription itself
        },
        {
            "name": "Spotify",
            "price": "17",
            "currency": "Euro",
            "category": "Music",
            "date": "2024-06-21",
            "payer": "Your name"
            "days": "1"
        }
    ]

}
```

This is the resulting object you should receive on the webhook.

**Comment by koenigderorangen** [comment, marked as answer]
I fixed it by examining how the PHP code handles the custom header field, specifying the custom header in this format:
![image](https://github.com/user-attachments/assets/cdcf2b0e-4834-46a3-9f8b-c9d061eabf20)
With that, I'm receiving the payload as JSON in Home Assistant:
![image](https://github.com/user-attachments/assets/7e35b678-9ebc-44c3-8a12-d8db1dcc1da5)

Extra: My automation code for sending notifications over the Home Assistant app to my phone looks like this:

```
alias: Notify Upcoming Subscriptions
description: Send notifications for upcoming subscription payments.
trigger:
  - platform: webhook
    webhook_id: YOURWEBHOOKID
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - repeat:
      count: "{{ trigger.json.subscriptions | length }}"
      sequence:
        - variables:
            subscription: "{{ trigger.json.subscriptions[repeat.index - 1] }}"
        - service: notify.mobile_app_YOURPHONE
          data:
            message: >
              {{ subscription['price'] }} {{ subscription['currency'] }} on {{
              subscription['date'] }}
            title: >
              Upcoming Payment by {{ subscription['name'] }} in {{
              subscription['days'] }} days
mode: single
```
