### ISSUE TITLE
unable to edit existing subscription

### ISSUE THREAD

**Issue by HendrikHaase** [ellite/Wallos#2]
mounted via portainer, docker-compose

```
version: '3.3'
services:
  wallos:
    container_name: wallos
    volumes:
      - wallos-db:/var/www/html/db
      - wallos-logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8282:80
    restart: unless-stopped
    image: 'bellamy/wallos:latest'
volumes:
  wallos-db:
    driver: local
  wallos-logos:
    driver: local
```

registration of first user works
login/logout works
adding subscriptions is working
can't edit subscriptions tho.

"Error
Failed to load subscription"

the get.php call returns a 200 with a valid json, example
```
{
    "id": 2,
    "name": "Spotify",
    "logo": null,
    "price": 14.99,
    "currency_id": 1,
    "next_payment": "2023-11-20",
    "frequency": 1,
    "cycle": 3,
    "notes": "",
    "payment_method_id": 1,
    "payer_user_id": 1,
    "category_id": 3,
    "notify": 0
}
```

but thats it.
