### ISSUE TITLE
Error When Adding

### ISSUE THREAD

**Issue by esmoyer** [ellite/Wallos#3]
Sorry, me again. I can't seem to add a new subscription I get:

![image](https://github.com/ellite/Wallos/assets/17444085/76142fc6-53e3-4c3a-8acf-7ece7ea00fba)

Using Firefox

docker-compose
```
services:
    wallos:
        image: 'bellamy/wallos:latest'
        restart: unless-stopped
        ports:
            - '9050:80'
        environment:
            - TZ=America/Chicago
        volumes:
            - '/appdata/wallos/logos:/var/www/html/images/uploads/logos'
            - '/appdata/wallos/db:/var/www/html/db'
        container_name: wallos
        network_mode: bridge
```

Nothing is showing in logs
