### ISSUE TITLE
Issue getting the container to start

### ISSUE THREAD

**Issue by Appoxo** [ellite/Wallos#30]
My docker-compose:
```yaml
---
version: "3.7"
service:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    depends_on:
      - traefik
    #expose: 
    #  - 8282
    ports:
      - 8282:8282
    networks:
      - service
    volumes:
      - /opt/docker/container/wallos/db:/var/www/html/db
      - /opt/docker/container/wallos/logos:/var/www/html/images/uploads/logos
    environment:
      TZ: ${TZ}
    labels:
      # Watchtower:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.scope: mainScope
      # Traefik:
      traefik.enable: true
      # Traefik rules for wallos:
      traefik.http.services.wallos.loadbalancer.server.port: 8282
      traefik.http.routers.wallos-local.entrypoints: 'http'
      traefik.http.routers.wallos-local.rule: 'Host(`wallos.${DOMAIN_INTERNAL}`)'
    restart: unless-stopped
```
I also used the example script in the readme
```shell
docker run -d --name wallos -v /opt/docker/container/wallos/db:/var/www/html/db \
-v /opt/docker/container/wallos/logos:/var/www/html/images/uploads/logos \
-e TZ=Europe/Berlin -p 8282:9999 --restart unless-stopped \ 
bellamy/wallos:latest
```
Output from the logs: 
```
[12-Nov-2023 14:53:34] NOTICE: fpm is running, pid 6
[12-Nov-2023 14:53:34] NOTICE: ready to handle connections
Database already exist. Checking for upgrades...
Table 'notifications' already exists.
Column 'notify' already exists in table 'subscriptions'.
```

I tried the following:
- Remove container and restart the compose -> Not working
- Remove container, pull image, restart compose -> Not working
- Double checked my compose -> All looked fine
- Tried the example script in the readme -> Not working
- Tried changing the host ports -> Not working

When trying to reach the container:
![grafik](https://github.com/ellite/Wallos/assets/17850993/c0dea5f6-0f96-4fc3-b1f9-3d6818d7cab3)

Additional pictures:  
![grafik](https://github.com/ellite/Wallos/assets/17850993/8e45cfbf-7e54-45f1-8676-045e7565a06a)
![grafik](https://github.com/ellite/Wallos/assets/17850993/489816e8-e9fe-4345-9f0a-d70253d753a5)

Any idea where I could l start looking? All other containers usually work fine

**Comment by ellite** [comment]
The exposed internal port in the container is port 80. I believe you're mapping the wrong port.

**Comment by Appoxo** [comment]
yeaahhhh... Thanks for fixing my stupidity. 😅
Access worked with this compose
```yaml
service:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    depends_on:
      - traefik
    expose: 
      - 80
    networks:
      - service
    domainname: appoxo.home
    volumes:
      - /opt/docker/container/wallos/db:/var/www/html/db
      - /opt/docker/container/wallos/logos:/var/www/html/images/uploads/logos
    environment:
      TZ: ${TZ}
    labels:
      # Watchtower:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.scope: mainScope
      # Traefik:
      traefik.enable: true
      # Traefik rules for wallos:
      traefik.http.services.wallos.loadbalancer.server.port: 80
      traefik.http.routers.wallos-local.entrypoints: 'http'
      traefik.http.routers.wallos-local.rule: 'Host(`wallos.${DOMAIN_INTERNAL}`)'
    restart: unless-stopped
```
Thanks for helping and for the work you put into this project. :)
I will now check it out!
