### ISSUE TITLE
Pushover Notification Not Working

### ISSUE THREAD

**Issue by mlclns** [ellite/Wallos#323]
I tried setting the "Alert *X* days before" to match one of my subscriptions, then in the container running ```php /var/www/html/endpoints/cronjobs/sendnotifications.php >> /var/log/cron/sendnotifications.log```, and the output to that file is just ```Nothing to notify.```

The test notification works in Wallos, however. Here is my docker-compose.yml
```
version: '3.0'

services:
  wallos:
    container_name: Wallos
    image: bellamy/wallos:latest
    ports:
      - "9061:80/tcp"
    environment:
      TZ: 'America/New_York'
      UID: "1000"
      GID: "1000"
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
```

Any help with this issue would be greatly appreciated!
