### ISSUE TITLE
[FEATURE REQUEST] Ability to run the container as an arbitrary user

### ISSUE THREAD

**Issue by bonny1992** [ellite/Wallos#33]
I'd like the ability to run the container under another user than root.
We could do this by leveraging environment variables:
```
-e PUID=1000 \
-e PGID=1000 \
```
or by using the `user` argument from docker:
```
user: 1000:1000
```

**Comment by garret** [comment]
I just found out about Wallos and to me this feature request would make it perfect. I tried with the `user: 1000:1000` but unfortunately it did not work. I hope it can be implemented something similar or even better as environment variables.

**Comment by ellite** [comment]
Hi. Quick update on this.
Finally took the time to investigate how this could be implemented and seems pretty straightforward.
Just need to test it and then I will release it.
Regards

**Comment by ellite** [comment]
Should be available now.

**Comment by basnijholt** [comment]
For anyone finding this @ellite implemented it here
https://github.com/ellite/Wallos/blob/b061f7e687ebaacf24a46fa476d34a3545c76ba7/startup.sh#L6-L10
which means setting `PUID` and `PGID` works :tada:

**Comment by robflate** [comment]
This isn't working for me. Files are owned by `82 - user #82`. I'm using Wallos v2.23.2;

```
services:  
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    restart: unless-stopped
    ports:
      - "8282:80/tcp"
    volumes:
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
```
Any advice appreciated. Thanks.
