### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by zzahkaboom24** [ellite/Wallos#466]
Wallos "2.14.1" in Docker.

Apparently, I just cant update to newer versions, tried deleting and recreating my container, nothing.
If I create a new container, or recreate the container without my volume, it runs some migrations and THEN it successfully shows me v2.20.0, but idk why not with my current volume, heres my compose, tho it seems fine as it is actually running:

```
version: '3.0'

volumes:
  wallos_data:
    name: wallos_data

services:
  wallos:
    container_name: Wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - 'wallos_data:/var/www/html'
    restart: always
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
```

**Comment by ellite** [comment]
I don't know if docker compose automatically pulls the latest image every time.

Maybe try to manually run

`docker pull bellamy/wallos:latest`

Before recreating the container.

**Comment by zzahkaboom24** [comment]
> I don't know if docker compose automatically pulls the latest image every time.
> 
> Maybe try to manually run
> 
> `docker pull bellamy/wallos:latest`
> 
> Before recreating the container.

I did. Even killed the container, removed it and the image. Atp I feel like making a backup of Wallos and restoring it on a new volume could be my best fix moving forward

**Comment by ellite** [comment]
Ah, wait. I think I know what is is.
You are mounting the full /var/www/html
You should only mount the db and the logos folders.

**Comment by zzahkaboom24** [comment]
> Ah, wait. I think I know what is is. You are mounting the full /var/www/html You should only mount the db and the logos folders.

ill try to replicate, other than that backup + restore worked, ill report in a sec thanks

**Comment by zzahkaboom24** [comment]
> Ah, wait. I think I know what is is. You are mounting the full /var/www/html You should only mount the db and the logos folders.

Yes. you were right. That was the reason.
I don't know why I mounted the full /var/www/html, let alone removed the mounts given in this repo's README, but I guess it happened. Thanks for helping me out, I upgraded my compose accordingly:
```
version: '3.0'

volumes:
  wallos_data:
    name: wallos_data

services:
  wallos:
    container_name: Wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - 'wallos_data:/var/www/html/db'
      - 'wallos_data:/var/www/html/images/uploads/logos'
    restart: always
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
```
