### ISSUE TITLE
[FEATURE REQUEST] System version in API

### ISSUE THREAD

**Issue by dannytsang** [ellite/Wallos#685]
I'd like to use [release argus](https://release-argus.io/) to check the deployed version of Wallos via API. This will allow the dashboard to show the latest version (from github) and the deployed version.

**Comment by ellite** [comment]
Looks easy enough. Do you know what the response from the api should look like?

**Comment by dannytsang** [comment]
The easiest way would be to return a json key value like {"version":"v2.42.2"} and match the tag you're using in git.

You could also return the above in an object on a more generalised end point like system status with other information as well.

Release Argus can use regex but the example above should cater for a simpler field select without regex.

Thanks for considering this.

**Comment by ellite** [comment]
on v2.43.0 there will be a new endpoint:

/status/version.php

`{"success":true,"title":"version","version":"v2.43.0","version_number":"2.43.0","notes":[]}`

**Comment by dannytsang** [comment]
Release Argus used the version number without the "v" prefix so not sure how it's got that. Either way, I'm glad you added it and it works. Don't forget to update.

I will try and submit a pull request to Release Argus example doc as well. For anyone else interested, here's my example:

Replace the **url** with your server and **xxx** with the API key from your profile in Wallos.
```
service:
  ellite/Wallos:
    latest_version:
      type: github
      url: ellite/Wallos
    deployed_version:
      method: GET
      url: http://wallos/api/status/version.php?api_key=xxx
      json: version_number
    notify:
      slack:
        params:
          icon: https://github.com/ellite/Wallos/raw/main/images/siteicons/wallos.png
    dashboard:
      icon: https://github.com/ellite/Wallos/raw/main/images/siteicons/wallos.png
      web_url: https://github.com/ellite/Wallos/releases
```
![image](https://github.com/user-attachments/assets/33cf9631-e3d4-45d9-815d-7ee7f3136bd8) ![image](https://github.com/user-attachments/assets/30d3ab08-2a4b-409f-ba6b-9df7c28621af)
