### ISSUE TITLE
Ability to customize fonts

### ISSUE THREAD

**Issue by abanichev** [ellite/Wallos#732]
The Barlow font, which is default, is not supported for some languages, which means subscription names not in English are rendered in a different font and look inconsistent. It would be great to have the option to choose the interface font in settings.

I tried solving this with Custom CSS, but adding a following custom css didn't change anything, still renders with Barlow:

```css
body {
  font-family: Helvetica, Arial, sans-serif;
}

input,
button,
select,
textarea {
  font-family: Helvetica, Arial, sans-serif;
}
```
